all:
  children:
    masters:
      hosts:
        master01:
          ansible_host: localhost
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    
    workers:
      hosts:
        worker01:
          ansible_host: 159.223.64.36
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3